spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        service: gulimall-seckill
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://169.254.139.10:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: 169.254.139.10:9876
  producer:
    group: seckill-producer-group
  consumer:
    group: seckill-consumer-group
  send-message-timeout: 3000  # 发送超时时间(ms)