spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://169.254.139.10:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    alicloud:
      access-key: LTAI5t7Z63u5HDPSHTroQqV6
      secret-key: oGeWrAjHAkYwgyfb1G9nBcxIDcrWfG
      region-id: cn-beijing
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-paopaozi
      sms:
        sign-name: 阿里云短信测试
  application:
    name: gulimall-third-party
