server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://169.254.139.10:3306/gulimall_wms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    alibaba:
#      seata:
#        tx-service-group: jilin #配置事务分组
#        #  配置seata注册中心，告诉微服务（seata client）怎么去访问seata server(TC)
#        registry:
#          type: nacos
#          nacos:
#            server-addr: 127.0.0.1:8848 #seata server 所在的nacos服务地址
#            application: seata-server-gulimall-ware #seata server 的服务名 默认为seata-server 如果未修改可不配置
#            username: nacos #nacos username
#            password: nacos #nacos password
#            group: SEATA_GROUP #seata server 所在分组名称，默认是 SEATA_GROUP ，没有修改可以不配置
#        config:
#          type: nacos
#          nacos:
#            server-addr: 127.0.0.1:8848 #seata server 所在的nacos服务地址
#            username: nacos #nacos username
#            password: nacos #nacos password
#            group: SEATA_GROUP #seata server 所在分组名称，默认是 SEATA_GROUP ，没有修改可以不配置
  application:
    name: gulimall-ware
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu: debug